/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VestingRouteImport } from './routes/vesting'
import { Route as StakingV1RouteImport } from './routes/staking-v1'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as Play2earnIntroRouteImport } from './routes/play2earn-intro'
import { Route as Play2earnRouteImport } from './routes/play2earn'
import { Route as GuildbankRouteImport } from './routes/guildbank'
import { Route as FarmsRouteImport } from './routes/farms'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmsIndexRouteImport } from './routes/farms/index'
import { Route as Play2EarnOatIdRouteImport } from './routes/play2Earn/$oatId'
import { Route as FarmsPoolRouteImport } from './routes/farms/$pool'

const VestingRoute = VestingRouteImport.update({
  id: '/vesting',
  path: '/vesting',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingV1Route = StakingV1RouteImport.update({
  id: '/staking-v1',
  path: '/staking-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const Play2earnIntroRoute = Play2earnIntroRouteImport.update({
  id: '/play2earn-intro',
  path: '/play2earn-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const Play2earnRoute = Play2earnRouteImport.update({
  id: '/play2earn',
  path: '/play2earn',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildbankRoute = GuildbankRouteImport.update({
  id: '/guildbank',
  path: '/guildbank',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsRoute = FarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsIndexRoute = FarmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmsRoute,
} as any)
const Play2EarnOatIdRoute = Play2EarnOatIdRouteImport.update({
  id: '/play2Earn/$oatId',
  path: '/play2Earn/$oatId',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsPoolRoute = FarmsPoolRouteImport.update({
  id: '/$pool',
  path: '/$pool',
  getParentRoute: () => FarmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/farms': typeof FarmsRouteWithChildren
  '/guildbank': typeof GuildbankRoute
  '/play2earn': typeof Play2earnRoute
  '/play2earn-intro': typeof Play2earnIntroRoute
  '/products': typeof ProductsRoute
  '/staking': typeof StakingRoute
  '/staking-v1': typeof StakingV1Route
  '/vesting': typeof VestingRoute
  '/farms/$pool': typeof FarmsPoolRoute
  '/play2Earn/$oatId': typeof Play2EarnOatIdRoute
  '/farms/': typeof FarmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guildbank': typeof GuildbankRoute
  '/play2earn': typeof Play2earnRoute
  '/play2earn-intro': typeof Play2earnIntroRoute
  '/products': typeof ProductsRoute
  '/staking': typeof StakingRoute
  '/staking-v1': typeof StakingV1Route
  '/vesting': typeof VestingRoute
  '/farms/$pool': typeof FarmsPoolRoute
  '/play2Earn/$oatId': typeof Play2EarnOatIdRoute
  '/farms': typeof FarmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/farms': typeof FarmsRouteWithChildren
  '/guildbank': typeof GuildbankRoute
  '/play2earn': typeof Play2earnRoute
  '/play2earn-intro': typeof Play2earnIntroRoute
  '/products': typeof ProductsRoute
  '/staking': typeof StakingRoute
  '/staking-v1': typeof StakingV1Route
  '/vesting': typeof VestingRoute
  '/farms/$pool': typeof FarmsPoolRoute
  '/play2Earn/$oatId': typeof Play2EarnOatIdRoute
  '/farms/': typeof FarmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/farms'
    | '/guildbank'
    | '/play2earn'
    | '/play2earn-intro'
    | '/products'
    | '/staking'
    | '/staking-v1'
    | '/vesting'
    | '/farms/$pool'
    | '/play2Earn/$oatId'
    | '/farms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guildbank'
    | '/play2earn'
    | '/play2earn-intro'
    | '/products'
    | '/staking'
    | '/staking-v1'
    | '/vesting'
    | '/farms/$pool'
    | '/play2Earn/$oatId'
    | '/farms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/farms'
    | '/guildbank'
    | '/play2earn'
    | '/play2earn-intro'
    | '/products'
    | '/staking'
    | '/staking-v1'
    | '/vesting'
    | '/farms/$pool'
    | '/play2Earn/$oatId'
    | '/farms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FarmsRoute: typeof FarmsRouteWithChildren
  GuildbankRoute: typeof GuildbankRoute
  Play2earnRoute: typeof Play2earnRoute
  Play2earnIntroRoute: typeof Play2earnIntroRoute
  ProductsRoute: typeof ProductsRoute
  StakingRoute: typeof StakingRoute
  StakingV1Route: typeof StakingV1Route
  VestingRoute: typeof VestingRoute
  Play2EarnOatIdRoute: typeof Play2EarnOatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vesting': {
      id: '/vesting'
      path: '/vesting'
      fullPath: '/vesting'
      preLoaderRoute: typeof VestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking-v1': {
      id: '/staking-v1'
      path: '/staking-v1'
      fullPath: '/staking-v1'
      preLoaderRoute: typeof StakingV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play2earn-intro': {
      id: '/play2earn-intro'
      path: '/play2earn-intro'
      fullPath: '/play2earn-intro'
      preLoaderRoute: typeof Play2earnIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play2earn': {
      id: '/play2earn'
      path: '/play2earn'
      fullPath: '/play2earn'
      preLoaderRoute: typeof Play2earnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guildbank': {
      id: '/guildbank'
      path: '/guildbank'
      fullPath: '/guildbank'
      preLoaderRoute: typeof GuildbankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/': {
      id: '/farms/'
      path: '/'
      fullPath: '/farms/'
      preLoaderRoute: typeof FarmsIndexRouteImport
      parentRoute: typeof FarmsRoute
    }
    '/play2Earn/$oatId': {
      id: '/play2Earn/$oatId'
      path: '/play2Earn/$oatId'
      fullPath: '/play2Earn/$oatId'
      preLoaderRoute: typeof Play2EarnOatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/$pool': {
      id: '/farms/$pool'
      path: '/$pool'
      fullPath: '/farms/$pool'
      preLoaderRoute: typeof FarmsPoolRouteImport
      parentRoute: typeof FarmsRoute
    }
  }
}

interface FarmsRouteChildren {
  FarmsPoolRoute: typeof FarmsPoolRoute
  FarmsIndexRoute: typeof FarmsIndexRoute
}

const FarmsRouteChildren: FarmsRouteChildren = {
  FarmsPoolRoute: FarmsPoolRoute,
  FarmsIndexRoute: FarmsIndexRoute,
}

const FarmsRouteWithChildren = FarmsRoute._addFileChildren(FarmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FarmsRoute: FarmsRouteWithChildren,
  GuildbankRoute: GuildbankRoute,
  Play2earnRoute: Play2earnRoute,
  Play2earnIntroRoute: Play2earnIntroRoute,
  ProductsRoute: ProductsRoute,
  StakingRoute: StakingRoute,
  StakingV1Route: StakingV1Route,
  VestingRoute: VestingRoute,
  Play2EarnOatIdRoute: Play2EarnOatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
